# https://appdaemon.readthedocs.io/en/latest/INSTALL.html#configuration
secrets: /home/hass/appdaemon/conf/secrets.yaml
appdaemon:
  # disable_apps: 1
  threads: 10
  production_mode: true
  app_dir: /home/hass/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://127.0.0.1:8123
      token: !secret token           # Add your Long-Lived Access Token here OR in the secrets file
hadashboard:
  dash_url: http://127.0.0.1:5050
  dashboard_dir: /home/hass/appdaemon/dashboards
