# https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#secrets

## This is preset to provide a working example.
## YOU SHOULD DISABLE THIS AND SET TOKEN INSTEAD
legacy_api: V96933UoA0qwXvMbignby

# Set your Long Live Access token below
token:
