homeassistant:
  ## Customize: https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize: !include customize.yaml
  ## Package files: https://www.home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named packages

#http:
#  ip_ban_enabled: True
#  login_attempts_threshold: 5

## List of components loaded by default_config can be found at the link below:
## https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/default_config/__init__.py
default_config:

## Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

## https://www.home-assistant.io/docs/z-wave/installation/#configuration
#zwave:
#  usb_path: /dev/cuaU0
#  network_key: !secret zwave_key
#  config_path: /srv/homeassistant/lib/python3.7/site-packages/python_openzwave/ozw_config

## https://www.home-assistant.io/components/zha/#configuration
#zha:
#  usb_path: /dev/cuaU1
#  database_path: /home/hass/homeassistant/zigbee.db
