# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets

# Enter your Long Lived Access Token for appdaemon
# https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#secrets
# https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#hass-authentication
appdaemon_token: "PASTE_LONG_LIVED_ACCESS_TOKEN_HERE"

## MQTT Broker
mqtt_user:
mqtt_passwd: 
  
## Z-Wave Security Key
## https://www.home-assistant.io/docs/z-wave/adding/#network-key
zwave_key:
