title: Quick Start for FreeNAS 11.3
subtitle: Home Assisstant Core (python virtualenv)
description: My quick start to Home Assisstant Core (python virtualenv) on FreeNAS 11.3

theme: jekyll-theme-architect

# Set Front matter defaults
defaults:
  # Defaults for all pages
  - scope:
      path: ""
    values:
      layout: default
